#!/bin/sh

SUBJ="/C=US/ST=New York/L=New York/O=Example/CN=elasticsearch.example.com"
if [ ! -f "$SSL_DIRECTORY"/server.crt ] && [ ! -f "$SSL_DIRECTORY"/server.key ]; then
  OPTS="req -nodes -new -x509 -sha256"
  openssl $OPTS -subj "$SUBJ" -keyout "$SSL_DIRECTORY"/server.key -out "$SSL_DIRECTORY"/server.crt 2> /dev/null
fi

AUTH_FILE="$DATA_DIRECTORY"/auth_basic.htpasswd
if [ -f "$AUTH_FILE" ]; then
  ln -sf "$AUTH_FILE" /etc/nginx
  sed -i 's/\# auth_basic/auth_basic/' /etc/nginx/nginx.conf
fi

if [ -n "$READONLY" ]; then
  sed -i 's/\#RO //g' /etc/nginx/nginx.conf
fi

/elasticsearch/bin/elasticsearch &
/usr/sbin/nginx $@
